void main() {
	uint i = gl_GlobalInvocationID.x;
	if (i >= uint(params.grid_dims.w)) {
		return;
	}
	vec3 pi = positions.data[i].xyz;
	vec3 vi = velocities.data[i].xyz;
	vec3 omega = vec3(0.0);
	FOREACH_NEIGHBOR(pi,
		vec3 d = pi - positions.data[j].xyz;
		float r2 = dot(d, d);
		if (r2 >= params.kernel.y) {
			continue;
		}
		vec3 vij = velocities.data[j].xyz - vi;
		omega += cross(vij, spiky_grad_r2(d, r2));
	)
	omega *= params.solver.w;
	predicted.data[i] = vec4(omega, length(omega));
}
