void main() {
	uint i = gl_GlobalInvocationID.x;
	if (i >= uint(params.grid_dims.w)) {
		return;
	}
	vec3 v_new = deltas.data[i].xyz;
	float temp = positions.data[i].w;
	velocities.data[i] = vec4(v_new, 0.0);
	vec3 p = positions.data[i].xyz;
	uint w = uint(params.misc.x);
	ivec2 texel = ivec2(int(i % w), int(i / w));
	// alpha: water = speed, lava = temperature
	imageStore(position_tex, texel, vec4(p, mix(length(v_new), temp, params.gravity.w)));
}
